name: Compile normal and plain PDF

# Controls when the workflow will run
on:
  # Triggers the workflow on push to any branch
  push:
  # Triggers the workflow when a release is created
  #release:
  #  types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Job to prepare the LaTeX files (convert SVG and modify LaTeX)
  prepare:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

  # Job to compile the LaTeX document
  compile:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      # Compile LaTeX document to PDF using XeLaTeX
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          compiler: lualatex

      # Upload compiled PDF for combination job
      - name: Upload compiled PDF
        uses: actions/upload-artifact@v4
        with:
          name: main-pdf
          path: main.pdf
          retention-days: 1
          compression-level: 0



